FROM python:3.6-slim-stretch

MAINTAINER ping@mirceaulinic.net

ARG VERSION="2019.2.0"

COPY --from=napalmautomation/napalm:develop /usr/local/lib/python3.6/site-packages/ /usr/local/lib/python3.6/site-packages/

COPY ./ /var/cache/salt-sproxy/

RUN pip --no-cache-dir install ciscoconfparse jxmlease ansible salt==$VERSION \
 && pip --no-cache-dir install /var/cache/salt-sproxy/

COPY ./roster /etc/salt/roster
COPY ./master /etc/salt/master
